Memo/fixed/views.py
from flask import Blueprint, render_template, abort
from models import db, Memo, Favorite, FixedPage
from sqlalchemy import func

fixed_bp = Blueprint('fixed', __name__, url_prefix='/fixed')


@fixed_bp.route("/<page_name>")
def static_page(page_name):
    page = FixedPage.query.filter_by(key=page_name).first()
    if not page:
        abort(404)
    # ---- ランキング用 ----
    raw_top10 = db.session.query(
        Memo,
        func.count(Favorite.id).label("like_count")
    ).outerjoin(Favorite).group_by(Memo.id).order_by(func.count(Favorite.id).desc()).limit(10).all()
    top10 = [
        {"memo": memo, "like_count": like_count}
        for memo, like_count in raw_top10
    ]
    return render_template(
        f'fixed/{page_name}.j2',
        page_title=page.title,
        key_visual=f'/static/images/fixed/{page.image or page_name + ".jpg"}',
        top10=top10
    )

Memo/templates/layout/footer.j2
<footer class="pt-5 text-body-secondary bg-body-tertiary">
  <div class="container">
    <div class="row">
      <div class="col-12 col-md-3 social-links d-flex gap-2 mb-3 mb-md-0">
          <a href="https://github.com/arihito" target="_blank" class="text-body-secondary fade-in fade-delay-1"><span class="fa-stack fa-lg"><i class="fa fa-square-o fa-stack-2x"></i><i class="fa fa-github fa-stack-1x"></i></span></a>
          <a href="https://twitter.com/arihitter" target="_blank" class="text-body-secondary fade-in fade-delay-2"><span class="fa-stack fa-lg"><i class="fa fa-square-o fa-stack-2x"></i><i class="fa fa-twitter fa-stack-1x"></i></span></a>
          <a href="https://www.facebook.com/arihito" target="_blank" class="text-body-secondary fade-in fade-delay-3"><span class="fa-stack fa-lg"><i class="fa fa-square-o fa-stack-2x"></i><i class="fa fa-facebook fa-stack-1x"></i></span></a>
          <a href="https://www.instagram.com/arihito.m" target="_blank" class="text-body-secondary fade-in fade-delay-4"><span class="fa-stack fa-lg"><i class="fa fa-square-o fa-stack-2x"></i><i class="fa fa-instagram fa-stack-1x"></i></span></a>
          <a href="https://www.linkedin.com/in/arihito-matsuda-8049596a/" target="_blank" class="text-body-secondary fade-in fade-delay-5"><span class="fa-stack fa-lg"><i class="fa fa-square-o fa-stack-2x"></i><i class="fa fa-linkedin fa-stack-1x"></i></span></a>
      </div>
      <div class="col-12 col-md-9">
        <p class="col-12 col-md-10 fade-in fade-delay-5">このFlask tech blogは、職業訓練校の課題として、Flaskアプリケーションの開発学習を目的に作成しています。<br>
        投稿記事のダミーテキストの一部は、AIによって生成しています。また、記事内容の正誤については、あくまで自身の理解をまとめたものですので、
        参考程度にご覧いただけますと幸いです。
        </p>
        <nav class="mb-4 mb-md-5">
            {% for key, val in FOOTER_NAV_PAGES.items() %}
                {% if not loop.first %}
                    <span class="fade-in fade-delay-{{ loop.index }} d-none d-md-inline">| </span>
                {% endif %}
                <span class="fade-in fade-delay-{{ loop.index }} d-inline d-md-none">・</span><a class="text-body-secondary mx-1 fade-in fade-delay-{{ loop.index }}" href="{{ url_for('fixed.static_page', page_name=key) }}">{{ val }}</a><br class="d-block d-md-none">
            {% endfor %}
        </nav>
      </div>
    </div>
  </div>
  <hr>
  <div class="container copyright text-center mt-3 pb-5 fade-in fade-delay-12">
      <p>&copy;2026 <span>Copyright</span> <strong class="px-1 sitename">Flask tech blog</strong> <span>All Rights Reserved</span></p>
      <div class="credits">
      </div>
  </div>
</footer>

Memo/templates/layout/globalnav.j2
<div class="container public_header">
    <header class="border-bottom py-3">
        <div class="container">
            <div class="row align-items-center">
                <!-- ロゴ -->
                <div class="col-12 col-md-6 text-center text-md-start mb-2 mb-md-0 fade-in fade-in-delay-8">
                    <a class="blog-header-logo text-body-emphasis text-decoration-none" href="{{ url_for('public.public_index') }}">tech blog</a>
                </div>
                <!-- 右側（未ログイン） -->
                {% if not current_user.is_authenticated %}
                  <div class="col-12 col-md-6">
                      <div class="btn-group d-flex justify-content-center justify-content-md-end">
                          <a class="btn btn-outline-secondary flex-fill flex-md-grow-0 fade-in fade-in-delay-16 {% if request.endpoint == 'auth.login' %}active{% endif %}" href="{{ url_for('auth.login') }}"><i class="fa fa-sign-in"></i> ログイン</a>
                          <a class="btn btn-outline-secondary flex-fill flex-md-grow-0 fade-in fade-in-delay-20 {% if request.endpoint == 'auth.register' %}active{% endif %}" href="{{ url_for('auth.register') }}"><i class="fa fa-user-plus"></i> 新規登録</a>
                      </div>
                  </div>
                <!-- 右側（ログイン済） -->
                {% else %}
                  <div class="col-12 col-md-6">
                      <div class="d-flex align-items-center justify-content-center justify-content-md-end gap-3">
                          <a class="text-body-secondary link-opacity-50-hover d-flex align-items-center" href="{{ url_for('memo.index') }}">
                              <img src="{{ url_for('static', filename='images/user/' ~ current_user.thumbnail) }}" alt="{{ current_user.username }}" class="user-icon me-2 fade-in fade-in-delay-8 rounded-circle" width="32" height="32">
                              <strong class="fade-in fade-in-delay-16">{{ current_user.username }} さん</strong></a>
                          <a class="btn btn-outline-secondary fade-in fade-in-delay-20" href="{{ url_for('auth.logout') }}"><i class="fa fa-sign-out"></i> ログアウト</a>
                      </div>
                  </div>
                {% endif %}
            </div>
        </div>
    </header>
    <div class="border-bottom mb-3">
        <nav class="navbar navbar-expand-md py-1">
            <!-- 左：トップ（常時表示） -->
            <a class="nav-link link-body-emphasis px-3 {% if not request.view_args %}active{% endif %}" href="{{ url_for('public.public_index') }}"><i class="fa fa-home"></i> トップ</a>
            <!-- 右：トグルボタン（スマホのみ表示） -->
            <button class="navbar-toggler d-md-none ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#globalNav"><span class="navbar-toggler-icon"></span></button>
            <!-- 折りたたみメニュー -->
            <div class="collapse navbar-collapse" id="globalNav">
                <ul class="navbar-nav ms-md-3 flex-column flex-md-row">
                    {% for key, val in GLOBAL_NAV_PAGES.items() %}
                        <li class="nav-item"><a class="nav-link link-body-emphasis px-3 fade-in fade-delay-{{ loop.index }} {% if request.endpoint == 'fixed.static_page' and request.view_args.page_name == key %}active{% endif %}" href="{{ url_for('fixed.static_page', page_name=key) }}">{{ val }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </nav>
    </div>
</div>

Memo/templates/layout/head.j2
<!DOCTYPE html>
<html lang="ja">
      <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>{% block page_title %}{{ SITE_NAME }}{% endblock %}</title>
            <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='images/other/favicon.ico') }}">
            <link rel="icon" type="image/png" href="{{ url_for('static', filename='images/other/icon.png') }}">
            <meta name="description" content="">
            <meta name="keywords" content="">
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
            <link rel="stylesheet" href=" https://cdn.jsdelivr.net/npm/pretty-checkbox@3.0/dist/pretty-checkbox.min.css">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github-dark.min.css">
            <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
            <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/sortablejs@1.15.3/Sortable.min.js"></script>
      </head>
      <body>
            {% block body %}
            {% endblock body %}
      </body>
</html>

Memo/templates/layout/mode.j2
{% extends 'layout/head.j2' %}

{% block body %}
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol id="check2" viewBox="0 0 16 16">
    <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z" />
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
    <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z" />
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
    <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z" />
    <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z" />
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
    <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z" />
    </symbol>
</svg>
<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
            id="bd-theme"
            type="button"
            aria-expanded="false"
            data-bs-toggle="dropdown"
            aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
            <use href="#circle-half"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow"
        aria-labelledby="bd-theme-text">
        <li>
            <button type="button"
                    class="dropdown-item d-flex align-items-center"
                    data-bs-theme-value="light"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                    <use href="#sun-fill"></use>
                </svg>
                明るい
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button"
                    class="dropdown-item d-flex align-items-center"
                    data-bs-theme-value="dark"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                    <use href="#moon-stars-fill"></use>
                </svg>
                暗い
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button"
                    class="dropdown-item d-flex align-items-center active"
                    data-bs-theme-value="auto"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                    <use href="#circle-half"></use>
                </svg>
                PC依存
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>
{% block container %}
{% endblock container %}
{% include 'layout/footer.j2' %}
<script src="https://unpkg.com/react@18/umd/react.development.js" crossorigin></script>
<script src="https://unpkg.com/react-dom@18/umd/react-dom.development.js" crossorigin></script>
<script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlightjs-line-numbers.js/2.8.0/highlightjs-line-numbers.min.js"></script>
<script src="{{ url_for('static', filename='js/main.js') }}"></script>
<script src="{{ url_for('static', filename='js/react.js') }}" type="text/babel"></script>
{% endblock body %}

Memo/templates/layout/sidemenu.j2
<div class="position-sticky top-0 pt-3">
    <ul class="nav flex-column">
        <li class="nav-item fade-in fade-in-delay-1"><a class="nav-link text-body-secondary fs-5 {% if request.endpoint == 'public.public_index' %}active{% endif %}" href="{{ url_for('public.public_index') }}"><i class="fa fa-wpforms me-2"></i>トップページ</a></li>
        <hr>
        <li class="nav-item fade-in fade-in-delay-2"><a class="nav-link text-body-secondary fs-5 {% if request.endpoint == 'memo.index' %}active{% endif %}" href="{{ url_for('memo.index') }}"><i class="fa fa-address-card me-2"></i>マイページ</a></li>
        <hr>
        <li class="nav-item fade-in fade-in-delay-3"><a class="nav-link text-body-secondary fs-5 {% if request.endpoint == 'memo.create' %}active{% endif %}" href="{{ url_for('memo.create') }}"><i class="fa fa-plus-square me-2"></i>記事追加</a></li>
        <hr>
        <li class="nav-item fade-in fade-in-delay-5"><a class="nav-link text-body-secondary fs-5 {% if request.endpoint == 'auth.edit' %}active{% endif %}" href="{{ url_for('auth.edit') }}"><i class="fa fa-user-circle-o me-2"></i>ユーザー編集</a></li>
        <hr>
        <li class="nav-item fade-in fade-in-delay-4"><a class="nav-link text-body-secondary fs-5 {% if request.endpoint and request.endpoint.startswith('admin.index') %}active{% endif %}" href="{{ url_for('admin.index') }}"><i class="fa fa-shield me-2"></i>管理者専用</a></li>
    </ul>
    <hr>
    <h6 class="text-body-secondary fs-5 ms-4 ps-2 mt-4 pt-2 mb-3 font-bold"><i class="fa fa-file-code-o me-2"></i> 開発関連資料</h6>
    <div class="accordion" id="accordionPanelsStayOpenExample">
        <div class="accordion-item">
            <h2 class="accordion-header">
                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseThree"><i class="fa fa-book me-2"></i>利用サービスガイド</button>
            </h2>
            <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse show">
                <div class="accordion-body">
                    <ul class="nav flex-column">
                        <li class="nav-item fade-in fade-in-delay-12"><a class="nav-link text-body-secondary"href="https://flask.palletsprojects.com/en/stable/" target="_blank"><i class="fa fa-flask me-2"></i>Flask</a></li>
                        <hr>
                        <li class="nav-item fade-in fade-in-delay-13"><a class="nav-link text-body-secondary"href="https://getbootstrap.jp/docs/5.3/getting-started/introduction/" target="_blank"><i class="fa fa-bold me-2"></i>Bootstrap5.3</a></li>
                        <hr>
                        <li class="nav-item fade-in fade-in-delay-14"><a class="nav-link text-body-secondary"href="https://fontawesome.com/v4/icons/" target="_blank"><i class="fa fa-font-awesome me-2"></i>FontAwesome4.7</a></li>
                        <hr>
                        <li class="nav-item fade-in fade-in-delay-15"><a class="nav-link text-body-secondary"href="https://platform.claude.com/docs/ja/home" target="_blank"><i class="fa fa-snowflake-o me-2"></i>ClaudeAPI</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>