csv_ai/product/views.py
from flask import Blueprint,render_template, request, redirect, url_for, flash
from models import db, Product
from forms import ProductCreateForm, ProductUpdateForm
from flask_login import login_required

# authのBlueprint
product_bp = Blueprint('product', __name__, url_prefix='/product')

# ルーティング

# トップ画面へ遷移
@product_bp.route("/top", methods=["GET"])
@login_required
def top():
    # 商品情報全件取得
    products = Product.query.all()
    # 画面遷移
    return render_template("product/top.html", products=products)

# 製品登録(Form使用)
@product_bp.route("/create", methods=["GET", "POST"])
@login_required
def create():
    # Formインスタンス生成
    form = ProductCreateForm()
    if form.validate_on_submit():
        # データ入力取得
        product_id = form.product_id.data
        product_name = form.product_name.data
        price = form.price.data
        released_date = form.released_date.data
        # 登録処理
        product = Product(product_id = product_id, product_name = product_name, price = price, released_date = released_date)
        db.session.add(product)
        db.session.commit()
        # 画面遷移
        flash("登録しました")
        return redirect(url_for("product.top"))
    # GET時
    # 画面遷移
    return render_template("product/create_form.html", form=form)

# 更新(Form使用)
@product_bp.route("/update/<int:product_id>", methods=["GET", "POST"])
@login_required
def update(product_id):
    # データベースからmemo_idに一致するメモを取得し、見つからない場合は404エラーを表示
    target_data = Product.query.get_or_404(product_id)
    # Formに入れ替え
    form = ProductUpdateForm(obj=target_data)
    if request.method == 'POST' and form.validate():
        # 変更処理
        target_data.product_name = form.product_name.data
        target_data.price = form.price.data
        target_data.released_date = form.released_date.data
        db.session.commit()
        # フラッシュメッセージ
        flash("変更しました")
        # 画面遷移
        return redirect(url_for("product.top"))
    # GET時
    # 画面遷移
    return render_template("product/update_form.html", form=form, edit_id=target_data.product_id)

# 削除
@product_bp.route("/delete/<int:product_id>")
@login_required
def delete(product_id):
    # データべースからmemo_idに一致するメモを取得し、見つからない場合は404エラーを表示
    product = Product.query.get_or_404(product_id)
    # 削除処理
    db.session.delete(product)
    db.session.commit()
    # 画面遷移
    return redirect(url_for("product.top"))

csv_ai/templates/product/create_form.html
{% extends "base.html" %}

{% block content %}

    <h1>新しいメモ作成</h1>
    {% from "_formhelpers.html" import render_field %}
    <form method="POST" action="{{ url_for('product.create') }}" >
        {{ form.hidden_tag() }}

        {{ render_field(form.product_id) }}
        {{ render_field(form.product_name) }}
        {{ render_field(form.price) }}
        {{ render_field(form.released_date) }}

        {{ form.submit }}
    </form>

    <a href="{{ url_for('product.top') }}">戻る</a>

{% endblock %}

csv_ai/templates/product/summary.html
{% extends "base.html" %}

{% block content %}
    {% if summary_table %}
        <form action="{{ url_for('product.reset') }}" method="post">
            <p>レビュー情報をリセット<button type="submit">リセット</button></p>
        </form>
        <br/>
    {% else %}
        <p>レビューCSVをアップロード</p>
        <form action="{{ url_for('product.upload') }}" method="post" enctype="multipart/form-data">
            <input type="file" name="file" accept=".csv" required>
            <button type="submit">アップロード</button>
        </form>
        <br/>
    {% endif %}

    <h1>商品別 平均スコア</h1>
    {% if summary_table %}
        <img src="data:image/png;base64,{{ img_base64 }}" alt="平均スコアグラフ">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <ul>
                    {% for msg in messages %}
                        <li>{{ msg }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        {% endwith %}

        <h2>製品番号別 総評</h2>
        <table style="border-collapse: collapse; width: 100%;">
            <thead>
                <tr>
                    {% for header in summary_table[0].keys() %}
                    <th style="border: 1px solid #000; padding: 8px; text-align: center; font-weight: bold;">
                    {{ header }}
                    </th>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                {% for row in summary_table %}
                <tr>
                {% for value in row.values() %}
                <td style="border: 1px solid #000; padding: 8px;">
                    {{ value }}
                </td>
                {% endfor %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>レビューデータがありません。</p>
    {% endif %}
        <a href="{{ url_for('product.top') }}">戻る</a>
{% endblock %}

csv_ai/templates/product/top.html
{% extends "base.html" %}

{% block content %}

    <h1>製品一覧</h1>
    {% if products == [] %}
        <p>製品は登録されていません</p>
    {% else %}
    <table  class="table table-sm table-hover table-borderless">
        <tr class="border-bottom">
            <th>製品ID</th><th>製品名</th><th>価格</th><th>発売日</th><th>編集</th>
        </tr>
        {% for product in products %}
        <tr class="border-bottom">
            <td>{{ product.product_id }}</td>
            <td>{{ product.product_name }}</td>
            <td>{{ product.price }}</td>
            <td>{{ product.released_date.strftime('%Y-%m-%d') }}</td>
            <td>
                <a href="{{ url_for('product.update', product_id=product.product_id) }}"
                        class="btn btn-outline-primary btn-sm">変更</a>
                <a href="{{ url_for('product.delete', product_id=product.product_id) }}"
                        class="btn btn-outline-primary btn-sm">削除</a>
            </td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
    <!-- flashメッセージ -->
    {% for message in get_flashed_messages() %}
    <div style="color: blue;">
        {{ message }}
    </div>
    {% endfor %}
    <!-- flashメッセージ -->
    <a href="{{ url_for('product.create') }}">製品登録</a>
{% endblock %}

csv_ai/templates/product/update_form.html
{% extends "base.html" %}

{% block content %}

    <h1>商品内容を変更</h1>
    {% from "_formhelpers.html" import render_field %}

    <form method="POST" action="{{ url_for('product.update', product_id=edit_id) }}" >
        {{ form.hidden_tag() }}

        {{ render_field(form.product_id, readonly=true) }}    
        {{ render_field(form.product_name) }}
        {{ render_field(form.price) }}
        {{ render_field(form.released_date) }}

        {{ form.submit }}
    </form>

    <a href="{{ url_for('product.top') }}">戻る</a>

{% endblock %}